FROM parrotsec/parrot-core

# Actualiza el sistema
RUN apt-get update && \
    apt-get dist-upgrade -y

# Instala net-tools y otros paquetes que puedas necesitar
RUN apt-get install -y net-tools

# Directorio compartido
VOLUME /tmp/compartido

CMD ["/bin/bash"]
